import Head from 'next/head';
import EventList from '@/components/events/EventList';
import { getFeaturedEvents } from '@/dummy-data';
export default function Home() {
  const filteredevents = getFeaturedEvents();
  return (
    <>
      <Head>
        <title>Next-Event</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>This is the home page of the app</h1>
      <EventList events={filteredevents} />
    </>
  );
}
