import Head from 'next/head';
import EventList from '@/components/events/EventList';
import { getFeaturedEvents } from '@/helpers/api-util';
import { DummyData } from '@/dummy-data';
const Home = (props: { events: DummyData[] }) => {
  return (
    <>
      <Head>
        <title>Next-Event</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <EventList events={props.events} />
    </>
  );
};

export const getStaticProps = async () => {
  const events = await getFeaturedEvents();
  return {
    props: {
      events: events,
    },
    revalidate: 1800,
  };
};
export default Home;
